### PR TITLE
Update URL in gemspec and travis

### PR DESCRIPTION
**Pull request by lzap**
Similarly as in the other gem, fixes travis as well.

### CODE REVIEW

**Comment by lzap** [comment]
Oh we have a parsing error [!] There was an error while loading `journald-native.gemspec`: undefined method `match?' for /^(COPYING|\.|spec\/)/:Regexp. Bundler cannot continue.

**Comment by lzap** [comment]
Yeah that's #define ENOENT  2 /* No such file or directory */ looking into it. I've added Ruby 2.4 as new tested version.

**Comment by lzap** [comment]
Rerunning with `strace`, looks like some kind of sandboxing in an container.

**Comment by lzap** [comment]
Ok I can confirm, systemd-journald is not running in that container:

```
socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 9
getsockopt(9, SOL_SOCKET, SO_SNDBUF, [212992], [4]) = 0
setsockopt(9, SOL_SOCKET, SO_SNDBUF, [8388608], 4) = 0
sendmsg(9, {msg_name(29)={sa_family=AF_LOCAL, sun_path="/run/systemd/journal/socket"}, msg_iov(5)=[{"MESSAGE=test", 12}, {"\n", 1}, {"SYSLOG_IDENTIFIER=", 18}, {"ruby", 4}, {"\n", 1}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 ENOENT (No such file or directory)
```

I will try to start it from `.travis.yml` but I guess that will not work, in that case I noticed there is some dummy mode, can we at least run tests in the dummy mode to ensure Ruby part works?

**Comment by lzap** [comment]
Sooo, this is now testing at least compilation against Ubuntu systemd libraries, then it recompiles it in dummy mode and performs tests with dummy mode (not talking to systemd). What you think? Better than nothing I guess! Ready for review.

**Comment by sandfoxme** [comment]
@lzap well, ruby part is vitually nonexistent here so there is no much sense in testing it. But maybe it's ok for a start

**Comment by lzap** [comment]
Yeah right, Travis is unknown territory for me, I tried hard to understand but was not able to find out how to run tests manually.

**Pull request merged**
